spring:
  application:
    name: "Marketplace API"
  datasource:
    url: jdbc:h2:mem:marketplace
    username: sa
    password: h2pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console